version: 2

models:   
  - name: published_activities
    description: "Published, deduplicated activities model with key fields. Strictly one row per IATI Identifier, possibly with loss of data."
    tests:
      - unique:
          column_name: iatiidentifier
      - dbt_utils.cardinality_equality:
          field: iatiidentifier
          to: source('iati_postgres', 'activity')
    columns:
      - name: iatiidentifier
        description: "Unique IATI Identifier"
      - name: title_narrative
        description: "Activity title narrative text"
      - name: reportingorg_ref
        description: "Reference code for the reporting organisation"
      - name: reportingorg_narrative
        description: "Narrative name of the reporting organisation"
      - name: reportingorg_type
        description: "Type code for the reporting organisation"
      - name: activitystatus_code
        description: "Status code of the activity"
      - name: plannedstart
        description: "Planned start date of the activity"
      - name: plannedend
        description: "Planned end date of the activity"
      - name: actualstart
        description: "Actual start date of the activity"
      - name: actualend
        description: "Actual end date of the activity"
      - name: lastupdateddatetime
        description: "Date and time when the activity was last updated"
      - name: hierarchy
        description: "Hierarchy level of the activity"
      - name: dportal_link
        description: "Link to the activity on D-Portal"

  - name: published_organisations
    description: "Published, deduplicated organisations model with key fields. Strictly one row per Organisation Identifier, possibly with loss of data."
    tests:
      - unique:
          column_name: organisationidentifier
    columns:
      - name: organisationidentifier
        description: "Unique Organisation Identifier"
        tests:
          - not_null
      - name: name_narrative
        description: "Organisation name narrative text"
      - name: hierarchy
        description: "Hierarchy level of the organisation"
      - name: reportingorg_ref
        description: "Reference code for the reporting organisation"

  - name: phantom_organisations
    description: "List of organisations that are referenced in the participatingorg, transaction, and organisation_recipientorgbudget tables, but are not present in the organisation or otheridentifier tables."
    tests:
      - unique:  # Ensure each phantom org ID appears only once (if grouping happens before this)
          column_name: reference
      - not_null:
          column_name: reference
      - not_null:
          column_name: distinct_narratives
      - not_null:
          column_name: phantom_in_participatingorg
      - not_null:
          column_name: phantom_in_transaction_provider
      - not_null:
          column_name: phantom_in_transaction_receiver
      - not_null:
          column_name: phantom_in_orgbudget_recipient
    columns:
      - name: reference
        description: "Unique Organisation Identifier"
      - name: distinct_narratives
        description: "Array of distinct narratives for the phantom organisation"
      - name: phantom_in_participatingorg
        description: "Boolean flag indicating if the phantom organisation is referenced in the participatingorg table"
      - name: phantom_in_transaction_provider
        description: "Boolean flag indicating if the phantom organisation is referenced in the transaction table as a provider"
      - name: phantom_in_transaction_receiver
        description: "Boolean flag indicating if the phantom organisation is referenced in the transaction table as a receiver"
      - name: phantom_in_orgbudget_recipient
        description: "Boolean flag indicating if the phantom organisation is referenced in the organisation_recipientorgbudget table"

  - name: phantom_activities
    description: "List of activity identifiers that are referenced in various tables but do not exist in the main activity table."
    columns:
      - name: phantom_activity_identifier
        description: "The IATI activity identifier that was referenced but not found in the activity table."
        tests:
          - not_null
      - name: source_column
        description: "The specific table and column where the phantom reference was found (e.g., 'relatedactivity.ref')."
        tests:
          - not_null
      - name: source_activity_id
        description: "The IATI identifier of the activity record that contained the phantom reference."
        tests:
          - not_null

  - name: participation_links
    description: "Represents the participation of an organisation in an activity, including their role."
    columns:
      - name: activity_id
        description: "The IATI identifier of the activity."
        tests: [not_null]
      - name: organisation_id
        description: "The IATI identifier of the participating organisation."
        tests: [not_null]
      - name: role_code
        description: "The IATI code for the organisation's role in the activity."
        tests: [not_null]
      - name: role_name
        description: "The human-readable name of the organisation's role."

  - name: financial_links
    description: "Represents aggregated financial flows between organisations and activities for specific transaction types, standardized to USD."
    columns:
      - name: source_node_id
        description: "The ID of the source node (organisation or activity reference)."
        tests: [not_null]
      - name: target_node_id
        description: "The ID of the target node (organisation or activity reference)."
        tests: [not_null]
      - name: source_node_type
        description: "The type of the source node ('ORGANISATION' or 'ACTIVITY')."
        tests: [not_null]
      - name: target_node_type
        description: "The type of the target node ('ORGANISATION' or 'ACTIVITY')."
        tests: [not_null]
      - name: transactiontype_code
        description: "The IATI code for the transaction type."
        tests: [not_null]
      - name: transaction_type_name
        description: "The human-readable name of the transaction type."
      - name: currency
        description: "The currency code for the transaction values."
        tests: [not_null]
      - name: total_value_usd
        description: "The total value of all transactions of this type between the source and target, standardized to USD."
        tests: [not_null]

  - name: funds_links
    description: "A simplified abstraction of financial transactions between activities, representing the flow of funds regardless of specific transaction types."
    columns:
      - name: source_node_id
        description: "The IATI activity identifier of the source activity (provider of funds)."
        tests: [not_null]
      - name: target_node_id
        description: "The IATI activity identifier of the target activity (receiver of funds)."
        tests: [not_null]
      - name: source_node_type
        description: "The type of the source node (always 'ACTIVITY' for this relationship)."
        tests: [not_null]
      - name: target_node_type
        description: "The type of the target node (always 'ACTIVITY' for this relationship)."
        tests: [not_null]
      - name: currency
        description: "The currency code for the transaction values (standardized to USD)."
        tests: [not_null]
      - name: total_value_usd
        description: "The total value of all funds flowing from the source activity to the target activity, standardized to USD."
        tests: [not_null]
  - name: hierarchy_links
    description: "Represents parent-child and sibling relationships between activities, compressing multiple declarations into one edge with `declared_by` property."
    tests:
      - not_null:
          column_name: source_node_id
      - not_null:
          column_name: target_node_id
      - not_null:
          column_name: relationship_type
    columns:
      - name: source_node_id
        description: "The IATI activity identifier of the source activity (the parent in parent-child relationships, or the lexicographically smaller of the pair in sibling relationships)."
      - name: target_node_id
        description: "The IATI activity identifier of the target activity (the child in parent-child relationships, or the lexicographically larger of the pair in sibling relationships)."
      - name: source_node_type
        description: "The type of the source node (always 'ACTIVITY')."
      - name: target_node_type
        description: "The type of the target node (always 'ACTIVITY')."
      - name: relationship_type
        description: "The type of relationship: 'PARENT_OF' or 'SIBLING_OF'."
      - name: declared_by
        description: "Array of activity identifiers that declared this relationship."
