name: 'iati_graph'
version: '1.0.0'
config-version: 2

profile: 'iati_graph'

# Define paths relative to this file (graph/)
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Removed deprecated target-path - dbt will use ./target/ by default
clean-targets: # These are relative to the project root (graph/)
  - "target"
  - "dbt_packages"
  - "logs"

models:
  iati_graph:
    # Configurations for models within the nodes directory
    nodes:
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
    # Configurations for models within the edges directory
    edges:
      +materialized: table
      +persist_docs:
        relation: true
        columns: true